package component:wasm-component;

world root {
    export render: func(payload: string) -> string;
    export render-html: func(payload: string) -> string;
    export describe: func(req: string) -> string;
}
